disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - variable_name
    - variable_name_min_length
    - type_name
    - function_parameter_count
    - shorthand_operator
# parameterized rules can be customized from this configuration file
line_length: 220
type_body_length: 400
function_body_length: 100
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - AppDelegate.swift
# parameterized rules can be customized from this configuration file
# line_length: 200
